/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import dono_dao.DonoDAO;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import principal.DonoDaCasa;
import principal.Residencia;
import principal.Venda;
import residencia_dao.ResidenciaDAO;
import venda_dao.VendaDAO;

/**
 *
 * @author giana
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtf_cpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_telefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtf_rendamensal = new javax.swing.JTextField();
        jtb_inserir = new javax.swing.JButton();
        jtb_alterar = new javax.swing.JButton();
        jtb_mostrar = new javax.swing.JButton();
        jtb_remover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabela1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jtf_cod_venda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_cpf_comprador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtf_codigo_residencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf_valor = new javax.swing.JTextField();
        jtb_inserir2 = new javax.swing.JButton();
        jtb_alterar2 = new javax.swing.JButton();
        jtb_mostrar2 = new javax.swing.JButton();
        jtb_remover2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_tabela3 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtf_codigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_area = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtf_endereco = new javax.swing.JTextField();
        jtb_inserir1 = new javax.swing.JButton();
        jtb_alterar1 = new javax.swing.JButton();
        jtb_mostrar1 = new javax.swing.JButton();
        jtb_remover1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_tabela2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o CPF:");

        jLabel2.setText("Digite o nome:");

        jLabel3.setText("Digite o telefone:");

        jLabel4.setText("Digite a renda mensal:");

        jtb_inserir.setText("Inserir");
        jtb_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_inserirActionPerformed(evt);
            }
        });

        jtb_alterar.setText("Alterar");
        jtb_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_alterarActionPerformed(evt);
            }
        });

        jtb_mostrar.setText("Mostrar");
        jtb_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_mostrarActionPerformed(evt);
            }
        });

        jtb_remover.setText("Remover");
        jtb_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_removerActionPerformed(evt);
            }
        });

        jt_tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "NOME", "TELEFONE", "RENDA MENSAL"
            }
        ));
        jScrollPane1.setViewportView(jt_tabela1);

        jButton3.setText("Mostrar por CPF");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar Ordenado ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_rendamensal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jtb_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jtb_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(jtb_mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtb_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtf_rendamensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_inserir)
                    .addComponent(jtb_alterar)
                    .addComponent(jtb_mostrar)
                    .addComponent(jtb_remover))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dono da residência", jPanel1);

        jLabel8.setText("Código da Venda:");

        jLabel9.setText("CPF do comprador:");

        jLabel10.setText("Código da residência:");

        jLabel12.setText("Valor:");

        jtb_inserir2.setText("Inserir");
        jtb_inserir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_inserir2ActionPerformed(evt);
            }
        });

        jtb_alterar2.setText("Alterar");
        jtb_alterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_alterar2ActionPerformed(evt);
            }
        });

        jtb_mostrar2.setText("Mostrar");
        jtb_mostrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_mostrar2ActionPerformed(evt);
            }
        });

        jtb_remover2.setText("Remover");
        jtb_remover2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_remover2ActionPerformed(evt);
            }
        });

        jt_tabela3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Venda", "CPF do comprador", "Código da residência", "Data", "Valor"
            }
        ));
        jScrollPane3.setViewportView(jt_tabela3);

        jButton1.setText("Calcular Média");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("Vendas efetuadas(ultimos 6 meses)");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Salvar Dados em txt");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtf_cpf_comprador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtf_codigo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtf_cod_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jtb_inserir2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jtb_alterar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(jtb_mostrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtb_remover2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtf_cod_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtf_cpf_comprador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtf_codigo_residencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_inserir2)
                    .addComponent(jtb_alterar2)
                    .addComponent(jtb_remover2)
                    .addComponent(jtb_mostrar2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vendas", jPanel2);

        jLabel5.setText("Digite o código da residência:");

        jLabel6.setText("Digite a área da residência:");

        jLabel7.setText("Digite o endereço da residência:");

        jtb_inserir1.setText("Inserir");
        jtb_inserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_inserir1ActionPerformed(evt);
            }
        });

        jtb_alterar1.setText("Alterar");
        jtb_alterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_alterar1ActionPerformed(evt);
            }
        });

        jtb_mostrar1.setText("Mostrar");
        jtb_mostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_mostrar1ActionPerformed(evt);
            }
        });

        jtb_remover1.setText("Remover");
        jtb_remover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_remover1ActionPerformed(evt);
            }
        });

        jt_tabela2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Área", "Endereço"
            }
        ));
        jScrollPane2.setViewportView(jt_tabela2);

        jButton2.setText("Mostrar por Endereço");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jtb_inserir1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtb_mostrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jtb_remover1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_area, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jtb_alterar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(104, 104, 104)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtf_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtb_inserir1)
                    .addComponent(jtb_alterar1)
                    .addComponent(jtb_mostrar1)
                    .addComponent(jtb_remover1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Residência", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_inserirActionPerformed
        DonoDAO donoAcoes;

        try {
            donoAcoes = new DonoDAO();
            String cpf = jtf_cpf.getText(), nome = jtf_nome.getText(), telefone = jtf_telefone.getText();
            float renda_mensal = Float.parseFloat(jtf_rendamensal.getText());

            DonoDaCasa dono = new DonoDaCasa();

            dono.setCpf(cpf);
            dono.setNome(nome);
            dono.setTelefone(telefone);
            dono.setRenda_mensal(renda_mensal);
            donoAcoes.adicionarDono(dono);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_inserirActionPerformed

    private void jtb_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_alterarActionPerformed

        DonoDAO donoAcoes;

        try {
            donoAcoes = new DonoDAO();
            String cpf = jtf_cpf.getText(), nome = jtf_nome.getText(), telefone = jtf_telefone.getText();
            float renda_mensal = Float.parseFloat(jtf_rendamensal.getText());

            DonoDaCasa dono = new DonoDaCasa();

            dono.setCpf(cpf);
            dono.setNome(nome);
            dono.setTelefone(telefone);
            dono.setRenda_mensal(renda_mensal);
            donoAcoes.alterar(dono);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_alterarActionPerformed

    private void jtb_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_mostrarActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela1.getModel();
        ArrayList<DonoDaCasa> al_listaDonos;
        DonoDAO donoDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            donoDAO = new DonoDAO();
            al_listaDonos = donoDAO.ListaCompleta();
            for (int i = 0; i < al_listaDonos.size(); i++) {
                Object[] dados = {al_listaDonos.get(i).getCpf(), al_listaDonos.get(i).getNome(), al_listaDonos.get(i).getTelefone(), al_listaDonos.get(i).getRenda_mensal()};
                dtm_tabela.addRow(dados);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_mostrarActionPerformed

    private void jtb_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_removerActionPerformed
        try {
            DonoDAO donoAcoes = new DonoDAO();
            donoAcoes.remover(jtf_cpf.getText());

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_removerActionPerformed

    private void jtb_inserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_inserir1ActionPerformed
        ResidenciaDAO residenciaAcoes;

        try {
            residenciaAcoes = new ResidenciaDAO();
            int codigo = Integer.parseInt(jtf_codigo.getText());
            float area = Float.parseFloat(jtf_area.getText());
            String endereco = jtf_endereco.getText();

            Residencia residencia = new Residencia();

            residencia.setCod_residencia(codigo);
            residencia.setArea(area);
            residencia.setEndereco(endereco);
            residenciaAcoes.adicionarResidencia(residencia);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_inserir1ActionPerformed

    private void jtb_alterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_alterar1ActionPerformed
        ResidenciaDAO residenciaAcoes;

        try {
            residenciaAcoes = new ResidenciaDAO();
            int codigo = Integer.parseInt(jtf_codigo.getText());
            float area = Float.parseFloat(jtf_area.getText());
            String endereco = jtf_endereco.getText();

            Residencia residencia = new Residencia();

            residencia.setCod_residencia(codigo);
            residencia.setArea(area);
            residencia.setEndereco(endereco);
            residenciaAcoes.alterar(residencia);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_alterar1ActionPerformed

    private void jtb_mostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_mostrar1ActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela2.getModel();
        ArrayList<Residencia> al_listaResidencias;
        ResidenciaDAO residenciaDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            residenciaDAO = new ResidenciaDAO();
            al_listaResidencias = residenciaDAO.ListaCompleta1();
            for (int i = 0; i < al_listaResidencias.size(); i++) {
                Object[] dados = {al_listaResidencias.get(i).getCod_residencia(), al_listaResidencias.get(i).getArea(), al_listaResidencias.get(i).getEndereco()};
                dtm_tabela.addRow(dados);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_mostrar1ActionPerformed

    private void jtb_remover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_remover1ActionPerformed
        try {
            ResidenciaDAO residenciaAcoes = new ResidenciaDAO();
            residenciaAcoes.remover(Integer.parseInt(jtf_codigo.getText()));

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_remover1ActionPerformed

    private void jtb_inserir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_inserir2ActionPerformed
        VendaDAO vendaAcoes;

        try {
            vendaAcoes = new VendaDAO();
            String cod_venda = jtf_cod_venda.getText();
            String fk_cpf = jtf_cpf_comprador.getText();
            int fk_cod_residencia = Integer.parseInt(jtf_codigo_residencia.getText());
            float valor = Float.parseFloat(jtf_valor.getText());

            Venda venda = new Venda();

            venda.setCod_venda(cod_venda);
            venda.setFk_cpf(fk_cpf);
            venda.setFk_cod_residencia(fk_cod_residencia);
            venda.setValor(valor);
            vendaAcoes.adicionarVenda(venda);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_inserir2ActionPerformed

    private void jtb_alterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_alterar2ActionPerformed
        VendaDAO vendaAcoes;

        try {
            vendaAcoes = new VendaDAO();
            String cod_venda = jtf_cod_venda.getText();
            String fk_cpf = jtf_cpf_comprador.getText();
            int fk_cod_residencia = Integer.parseInt(jtf_codigo_residencia.getText());
            float valor = Float.parseFloat(jtf_valor.getText());

            Venda venda = new Venda();

            venda.setCod_venda(cod_venda);
            venda.setFk_cpf(fk_cpf);
            venda.setFk_cod_residencia(fk_cod_residencia);
            venda.setValor(valor);
            vendaAcoes.alterar(venda);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_alterar2ActionPerformed

    private void jtb_mostrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_mostrar2ActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela3.getModel();
        ArrayList<Venda> al_listaVendas;
        VendaDAO vendaDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            vendaDAO = new VendaDAO();
            al_listaVendas = vendaDAO.ListaCompleta3();
            for (int i = 0; i < al_listaVendas.size(); i++) {
                Object[] dados = {al_listaVendas.get(i).getCod_venda(), al_listaVendas.get(i).getFk_cpf(), al_listaVendas.get(i).getFk_cod_residencia(), al_listaVendas.get(i).getDataDaVenda(), al_listaVendas.get(i).getValor()};
                dtm_tabela.addRow(dados);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_mostrar2ActionPerformed

    private void jtb_remover2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_remover2ActionPerformed
        try {
            VendaDAO vendaAcoes = new VendaDAO();
            vendaAcoes.remover(jtf_cod_venda.getText());

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtb_remover2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            VendaDAO vendaAcoes = new VendaDAO();
            ArrayList<Venda> al_listaVendas = vendaAcoes.ListaCompleta3();
            float media = 0;
            for (int i = 0; i < al_listaVendas.size(); i++) {
                media = media + al_listaVendas.get(i).getValor();
            }
            media = media / al_listaVendas.size();

            JOptionPane.showMessageDialog(null, "A média do valor das residencias é:" + media);

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela2.getModel();
        ArrayList<Residencia> al_listaResidencias;
        ResidenciaDAO residenciaDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            residenciaDAO = new ResidenciaDAO();
            al_listaResidencias = residenciaDAO.ListaCompleta1();
            for (int i = 0; i < al_listaResidencias.size(); i++) {
                if (al_listaResidencias.get(i).getEndereco().equalsIgnoreCase(jtf_endereco.getText())) {
                    Object[] dados = {al_listaResidencias.get(i).getCod_residencia(), al_listaResidencias.get(i).getArea(), al_listaResidencias.get(i).getEndereco()};
                    dtm_tabela.addRow(dados);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela1.getModel();
        ArrayList<DonoDaCasa> al_listaDonos;
        DonoDAO donoDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            donoDAO = new DonoDAO();
            al_listaDonos = donoDAO.ListaCompleta();
            for (int i = 0; i < al_listaDonos.size(); i++) {
                if (al_listaDonos.get(i).getCpf().equalsIgnoreCase(jtf_cpf.getText())) {
                    Object[] dados = {al_listaDonos.get(i).getCpf(), al_listaDonos.get(i).getNome(), al_listaDonos.get(i).getTelefone(), al_listaDonos.get(i).getRenda_mensal()};
                    dtm_tabela.addRow(dados);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela1.getModel();
        ArrayList<DonoDaCasa> al_listaDonos;
        DonoDAO donoDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            donoDAO = new DonoDAO();
            al_listaDonos = donoDAO.ListaOrdenada();
            for (int i = 0; i < al_listaDonos.size(); i++) {
                Object[] dados = {al_listaDonos.get(i).getCpf(), al_listaDonos.get(i).getNome(), al_listaDonos.get(i).getTelefone(), al_listaDonos.get(i).getRenda_mensal()};
                dtm_tabela.addRow(dados);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel dtm_tabela = (DefaultTableModel) jt_tabela3.getModel();
        ArrayList<Venda> al_listaVendas;
        VendaDAO vendaDAO;

        for (int i = dtm_tabela.getRowCount() - 1; i >= 0; i--) {
            dtm_tabela.removeRow(i);
        }

        try {
            vendaDAO = new VendaDAO();
            al_listaVendas = vendaDAO.ListaCompleta3();
            LocalDate today = LocalDate.now();
            LocalDate pastdate = today.minusMonths(6);
            for (int i = 0; i < al_listaVendas.size(); i++) {
                if (al_listaVendas.get(i).getDataDaVenda().isAfter(pastdate) && al_listaVendas.get(i).getDataDaVenda().isBefore(today)) {
                    Object[] dados = {al_listaVendas.get(i).getCod_venda(), al_listaVendas.get(i).getFk_cpf(), al_listaVendas.get(i).getFk_cod_residencia(), al_listaVendas.get(i).getDataDaVenda(), al_listaVendas.get(i).getValor()};
                    dtm_tabela.addRow(dados);
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        ArrayList<Venda> al_listaVendas = null;
        ArrayList<DonoDaCasa> al_listaDonos = null;
        ArrayList<Residencia> al_listaResidencias = null;
        try {
            VendaDAO vendaAcoes = new VendaDAO();
             al_listaVendas = vendaAcoes.ListaCompleta3();

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            DonoDAO donoAcoes = new DonoDAO();
             al_listaDonos = donoAcoes.ListaCompleta();

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            ResidenciaDAO residenciaAcoes = new ResidenciaDAO();
             al_listaResidencias = residenciaAcoes.ListaCompleta1();

        } catch (SQLException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Tela.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            FileWriter arq = new FileWriter("txt/DonoDasResidencias.txt");
            PrintWriter gravarArq = new PrintWriter(arq);
            for (int i = 0; i < al_listaDonos.size(); i++) {
                gravarArq.printf("\n");
                gravarArq.printf(al_listaDonos.get(i).toString());
            }
            arq.close();
            JOptionPane.showMessageDialog(null, "TXT dos proprietarios criado com sucesso.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
        
        try {
            FileWriter arq = new FileWriter("txt/Vendas.txt");
            PrintWriter gravarArq = new PrintWriter(arq);
            for (int i = 0; i < al_listaVendas.size(); i++) {
                gravarArq.printf("\n");
                gravarArq.printf(al_listaVendas.get(i).toString());
            }
            arq.close();
            JOptionPane.showMessageDialog(null, "TXT das vendas criado com sucesso.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
        
        try {
            FileWriter arq = new FileWriter("txt/Residencias.txt");
            PrintWriter gravarArq = new PrintWriter(arq);
            for (int i = 0; i < al_listaResidencias.size(); i++) {
                gravarArq.printf("\n");
                gravarArq.printf(al_listaResidencias.get(i).toString());
            }
            arq.close();
            JOptionPane.showMessageDialog(null, "TXT das residencias criado com sucesso.", "Alerta", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jt_tabela1;
    private javax.swing.JTable jt_tabela2;
    private javax.swing.JTable jt_tabela3;
    private javax.swing.JButton jtb_alterar;
    private javax.swing.JButton jtb_alterar1;
    private javax.swing.JButton jtb_alterar2;
    private javax.swing.JButton jtb_inserir;
    private javax.swing.JButton jtb_inserir1;
    private javax.swing.JButton jtb_inserir2;
    private javax.swing.JButton jtb_mostrar;
    private javax.swing.JButton jtb_mostrar1;
    private javax.swing.JButton jtb_mostrar2;
    private javax.swing.JButton jtb_remover;
    private javax.swing.JButton jtb_remover1;
    private javax.swing.JButton jtb_remover2;
    private javax.swing.JTextField jtf_area;
    private javax.swing.JTextField jtf_cod_venda;
    private javax.swing.JTextField jtf_codigo;
    private javax.swing.JTextField jtf_codigo_residencia;
    private javax.swing.JTextField jtf_cpf;
    private javax.swing.JTextField jtf_cpf_comprador;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_rendamensal;
    private javax.swing.JTextField jtf_telefone;
    private javax.swing.JTextField jtf_valor;
    // End of variables declaration//GEN-END:variables
}
